import {Api} from "/web/api.js";import {State} from "/web/state.js";import {Canvas} from "/web/canvas.js";
const api=new Api(),state=new State();new Canvas(document.querySelector("#canvas"),state);
const $=selector=>document.querySelector(selector),message=text=>{$("#message").textContent=text;setTimeout(()=>{$("#message").textContent=""},3500)};
let catalog=[];
async function health(){try{const h=await api.health();$("#healthText").textContent=`${h.mode} · ${h.version}`;$("#healthDot").style.background=h.ok?"#45d483":"#ff6978"}catch{$("#healthText").textContent="offline";$("#healthDot").style.background="#ff6978"}}
function renderCatalog(filter=""){const root=$("#nodeCatalog");root.replaceChildren();for(const item of catalog.filter(x=>`${x.label} ${x.type}`.toLowerCase().includes(filter.toLowerCase()))){const el=document.createElement("div");el.className="catalog-item";const title=document.createElement("span"),small=document.createElement("small");title.textContent=item.label;small.textContent=item.type;el.append(title,small);el.addEventListener("dblclick",()=>state.add(item.type,120+Math.random()*160,100+Math.random()*140));root.append(el)}}
async function loadProjects(){const items=await api.projects(),select=$("#projectSelect");select.replaceChildren(new Option("Select project",""),...items.map(x=>new Option(x.name,x.id)));if(items[0]){select.value=items[0].id;await loadWorkflows(items[0].id)}}
async function loadWorkflows(projectId){const items=await api.workflows(projectId),select=$("#workflowSelect");select.replaceChildren(new Option("New workflow",""),...items.map(x=>new Option(x.name,x.id)));if(items[0]){select.value=items[0].id;state.setWorkflow(items[0])}else state.setWorkflow(null)}
async function loadJobs(){try{const items=await api.jobs(),root=$("#jobs");root.replaceChildren();for(const item of items.slice(0,20)){const el=document.createElement("div");el.className="job";el.textContent=item.id;const status=document.createElement("span");status.textContent=item.status;el.append(status);root.append(el)}}catch{}}
state.subscribe(()=>{const node=state.nodes.find(x=>x.id===state.selected),form=$("#inspector"),empty=$("#inspectorEmpty");form.hidden=!node;empty.hidden=!!node;if(node){$("#nodeId").value=node.id;$("#nodeType").value=node.type;$("#nodeParams").value=JSON.stringify(node.params||{},null,2)}});
$("#nodeSearch").addEventListener("input",e=>renderCatalog(e.target.value));$("#projectSelect").addEventListener("change",e=>loadWorkflows(e.target.value));$("#workflowSelect").addEventListener("change",async e=>{const items=await api.workflows($("#projectSelect").value);state.setWorkflow(items.find(x=>x.id===e.target.value)||null)});
$("#newProject").addEventListener("click",async()=>{const name=prompt("Project name");if(!name)return;await api.createProject({name});await loadProjects();message("Project created")});
$("#clearCanvas").addEventListener("click",()=>{if(confirm("Clear canvas?")){state.nodes=[];state.selected=null;state.emit()}});
$("#inspector").addEventListener("submit",e=>{e.preventDefault();try{state.update(state.selected,{params:JSON.parse($("#nodeParams").value||"{}")});message("Node updated")}catch(error){alert(error.message)}});$("#deleteNode").addEventListener("click",()=>state.remove(state.selected));
$("#saveWorkflow").addEventListener("click",async()=>{const projectId=$("#projectSelect").value;if(!projectId)return alert("Create or select a project first");const id=$("#workflowSelect").value;if(id)state.setWorkflow(await api.updateWorkflow(id,state.definition()));else{const name=prompt("Workflow name","Untitled workflow")||"Untitled workflow";state.setWorkflow(await api.createWorkflow({project_id:projectId,name,definition:state.definition()}));await loadWorkflows(projectId)}message("Workflow saved")});
$("#runWorkflow").addEventListener("click",async()=>{const id=$("#workflowSelect").value;if(!id)return alert("Save the workflow first");const job=await api.run(id,{});message(`Job ${job.id} queued`);setTimeout(loadJobs,500)});
(async()=>{await health();catalog=await api.nodes();renderCatalog();await loadProjects();await loadJobs();setInterval(health,15000);setInterval(loadJobs,3000)})().catch(error=>message(error.message));
